#!/usr/bin/env bash

# almost identical to: https://github.com/mislav/dotfiles/blob/master/install

set -e

here="$(cd "${0%/*}"; pwd)"

for file in "$here"/*; do
  name="$(basename "$file" .md)"
  [[ $name = bin ]] && dotname="$name" || dotname=".${name}"

  if ! [[ "install readme" =~ $name || $name =~ ".plist" || -e ~/$dotname || -d $file/.git ]]; then
    ln -sfhv ${file#$HOME/} "${HOME}/${dotname}"
  fi
done

# this part is not used at the moment
while read file; do
  bin="bin/${file##*/}"
  fullbin="${here}/${bin}"

  if ! [[ -e "${here}/${file}" ]]; then
    echo "not found: ${file}" >&2
  elif ! [[ -e $fullbin ]]; then
    ln -sfhv "../${file}" "$fullbin"
    echo "$bin" >> "${here}/.git/info/exclude"
  fi
done < "${here}/.external"
