#!/usr/bin/env bash

# almost identical to: https://github.com/mislav/dotfiles/blob/master/install

set -e

here="$(cd "${0%/*}"; pwd)"

for file in "$here"/*; do
  name="$(basename "$file" .md)"
  [[ $name = bin ]] && dotname="$name" || dotname=".${name}"

  if ! [[ "install readme README oh-my-zsh" =~ $name || $name =~ ".plist" || -e ~/$dotname || -d $file/.git ]]; then
    ln -sfhv ${file#$HOME/} "${HOME}/${dotname}"
  fi
done

# small hack to make sure that simple linking method below
# works on a brand new machine
mkdir -p "${HOME}/.oh-my-zsh/custom/plugins/basti"

while read file; do
  bin="bin/${file##*/}"
  fullbin="${here}/${bin}"
  linksource="${here}/${file}"
  linktarget="${HOME}/.${file}"

  if ! [[ -e "${here}/${file}" ]]; then
    echo "not found: ${file}" >&2
  elif [[ -e $linksource ]]; then
    # most likely not a bin/ file, but additional configuration like: oh-my-zsh/custom/basti.zsh-theme
    ln -sfhv "${linksource}" "${linktarget}"
  elif ! [[ -e $fullbin ]]; then
    ln -sfhv "../${file}" "$fullbin"
    echo "$bin" >> "${here}/.git/info/exclude"
  fi
done < "${here}/.external"
